### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by hstevanoski** [wle8300/uifx#12]
I am using uifx version 2.0.3 in a React project.
Sometimes (not always), for some reason I am getting the following error and the audio doesn't get played:

![image](https://user-images.githubusercontent.com/10324469/69980273-2e711d80-1530-11ea-8cf2-df87a1d32cdb.png)

This is where index.js:104 is indicating the error is (from the image above):

![image](https://user-images.githubusercontent.com/10324469/69980520-afc8b000-1530-11ea-86f4-3b947c7f84a3.png)

I googled this error and didn't manage to find anything related to uifx, so it might be a Google Chrome [related issue](https://stackoverflow.com/a/53167783/4156040).

I am using uifx to play a lightweight wav file in a Redux middleware.
I even tried surrounding my code in a try/catch block, but to no avail.

```js
import { ADD_NOTIFICATION } from "../actions/notificationsActions";
import UIfx from "uifx";
import notificationAudioFile from "../../notification.wav";

const notificationSound = new UIfx(notificationAudioFile);

const notificationMiddleware = store => next => action => {
  let result = next(action);

  switch (action.type) {
    case ADD_NOTIFICATION:
      try {
        notificationSound.play(); // <--------- HERE
      } catch (e) {
        console.log(e);
      }

      break;
  }

  return result;
};

export default notificationMiddleware;
```

**Comment by wle8300** [comment]
@hstevanoski Pls give me a few days and I'll look at this.

In the meantime, if you're able to provide a fix for this I'd definitely welcome it!

**Comment by wle8300** [comment]
Fixed! https://github.com/wle8300/uifx/pull/13
