### ISSUE TITLE
Uncaught Error: "Volume" must be an number between 0.0 and 1.0

### ISSUE THREAD

**Issue by nicolopezuruguayo** [wle8300/uifx#15]
I did exactly like the basic example and the advanced (http://www.wle8300.com/uifx-demo/) and it throws this error:

Uncaught Error: "Volume" must be an number between 0.0 and 1.0

**Comment by nicolopezuruguayo** [comment]
Destructuring volume value from config (line 31) in the build solves the problem. 

Obs:
1)  UIfx installed with npm.
2) Actually it should be fixed in the source, because in the package the file is transpiled to vanilla javascript, but it work because the browser understant it.

**Comment by wle8300** [comment]
Can you post your own code?

**Comment by nicolopezuruguayo** [comment]
I installed UIfx in another project and it works without any changes, both projects created with create-react-app. I got confused, but anyway it works in both cases with and without modifying it.

This is the modified code (line 31 upward) : 

`  
var validateVolume = function validateVolume({volume} = config) {
    var message = '"Volume" must be an number between 0.0 and 1.0';

    if (volume && typeof volume !== "number") throw Error(message);
    if (volume < 0 || volume > 1) throw Error(message);

    return volume ? volume : 1.0;
  };
`

**Comment by wle8300** [comment]
Great!

If everything is working fine, ill close this issue.

🙏
