### ISSUE TITLE
UIfx says: "had a problem playing..."

### ISSUE THREAD

**Issue by aentan** [wle8300/uifx#17]
```
import shutterSound from './shutter.mp3';

class SomePage extends Component {
  const shutterSnap = new UIfx(shutterSound);

  handleClick = () => {
    shutterSnap.play();
  }

  render() {
    return (
      <div onClick={handleClick}>Make Sound</div>
    );
  }
}
```

Sound doesn't play. I get this error:

UIfx says: "had a problem playing file: /static/media/shutter.c971ba75.mp3"

What am I doing wrong?

**Comment by wle8300** [comment]
Your code looks right. You don’t need a fat function for handleClick. Just do

handleClick = shutterSnap.play

You’ll want Check whether your mp3 file is corrupt. Try another mp3 that you know works

**Comment by aentan** [comment]
Oh I have other stuff in handleClick. Just simplified it.

Thing is if I put play in ComponentDidMount, it plays fine.

**Comment by aentan** [comment]
I just tested the code above. It plays fine. It's my actual code that's not OK. This is the actual code.

I'm trying to play a sound when `react-qr-reader` does a scan.

```
<QrReader
  delay={2000}
  onError={this.handleScanError}
  onScan={this.handleScan}
/>

handleScan = data => {
  if (data) {
    console.log(shutterSnap);
    shutterSnap.play();
  }
}
```

Is it conflicting with my web cam?

**Comment by aentan** [comment]
Ah turns out it works in Chrome but not Safari. I tried loading the actual mp3 and it said

Failed to load resource: Plug-in handled load

**Comment by wle8300** [comment]
Hmm that is definitely strange. The way Chrome/Safari handles mp3 files is identical. 

Wild guess: r u using SSR?

**Comment by wle8300** [comment]
Also that error msg: Plug-fin failed to load resource. That’s not an error message uifx throws. Try a stacktrace to find where that error was thrown
