### ISSUE TITLE
Playing same sound effect 2 times in rapid succession

### ISSUE THREAD

**Issue by fshsweden** [wle8300/uifx#18]
I have this sound file definition:
    this.kaching = new UIfx(kaching, {
      volume: 0.4, // number between 0.0 ~ 1.0
      throttleMs: 40
    });

I also have an event handler which plays this file. However if I get two events in rapid succession, I only hear the sound once. I log the event to the console so I can see that I get the events.

    onTrade(obj) {
      this.kaching.play();
    }

Apparently the second time fails since the sound file is already playing?

How can I make sure the file is played both times?

**Comment by wle8300** [comment]
This sounds like an implementation question 🤔

**Comment by fshsweden** [comment]
So It is not supposed to work if I write (for example):
    onTrade(obj) {
      this.kaching.play();
      this.kaching.play();
      this.kaching.play();
    }

How do you suggest I do that then, since as I understand it you dont return a Promise from the play() function, so I cant use 

     this.kaching.play().then(() => {
        // playing done, queue next mp3 to play....
      }).catch((err) => {
      });

**Comment by wle8300** [comment]
This is an implementation question. See the `throttle` config
