### ISSUE TITLE
Sound is not working on Safari

### ISSUE THREAD

**Issue by ONEKENO** [wle8300/uifx#19]
Sound is not working on Safari
It's also reproducible on the demo [http://www.wle8300.com/uifx-demo/](url) 
Please advise. Thanks.

macOS: Version 10.14.6
Safari: Version 13.0.5 (14608.5.12)

**Comment by wle8300** [comment]
@ONEKENO I can't test Safari directly but the `Audio` API is definitely available for Safari 13. You may want to check your implementation of UIfx
