### ISSUE TITLE
play() can only be initiated by a user gesture and cleaning up

### ISSUE THREAD

**Issue by RWOverdijk** [wle8300/uifx#20]
Get this error when playing a notification sound:

> play() can only be initiated by a user gesture

Is this for all sounds?

Also I'm curious how to clean up sounds when I'm done with them, they seem to linger in the DOM.

**Comment by wle8300** [comment]
What OPerating System are you getting these errors? It works on iOS and Android. 

Regarding the clean-up of HTML markup: uifx doesn’t do this BUT that would be an amazing feature to have. Great idea! 💡 Interested in creating a PR for this?

**Comment by RWOverdijk** [comment]
@wle8300 MacOS. :)

The issue is only if the user hasn't interacted with the page yet; which makes sense so it's not a huge deal.

> Interested in creating a PR for this?

Sure thing, might take a bit though.

**Comment by RWOverdijk** [comment]
Correction, even after interacting with the page I get this message.

**Comment by RWOverdijk** [comment]
Huh. [Howler](https://github.com/goldfire/howler.js) does work.

**Comment by wle8300** [comment]
Not sure what’s causing it. I did a lot of testing already.

You’ll want to check your implementation of uifx
