### ISSUE TITLE
Play seems to be delayed on mobile

### ISSUE THREAD

**Issue by itayganor** [wle8300/uifx#21]
Hi there and thanks for a great library!

I do have something that bothers me though:
Every time I play an audio from mobile, it feels like there's a tiny delay between clicking the button and actually hearing the audio.

It doesn't happen on Desktop, so it feels like the audio takes some time to load before playing.

Is there a way to fix this? maybe pre-load all files and just play on demand?

Thanks!

**Comment by wle8300** [comment]
It’s an iOS thing. You can Google: “iOS web tap delay”. It’s a notorious wrinkle that web people have to deal with

**Comment by itayganor** [comment]
> It’s an iOS thing. You can Google: “iOS web tap delay”. It’s a notorious wrinkle that web people have to deal with
> […](#)
> Sent from my iPhone
> On May 9, 2020, at 10:41 AM, Itay Ganor ***@***.***> wrote: Hi there and thanks for a great library! I do have something that bothers me though: Every time I play an audio from mobile, it feels like there's a tiny delay between clicking the button and actually hearing the audio. It doesn't happen on Desktop, so it feels like the audio takes some time to load before playing. Is there a way to fix this? maybe pre-load all files and just play on demand? Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm on Android actually. OnePlus 6. Trying to find a lightweight way to add sound effects to my game

**Comment by wle8300** [comment]
Hmm can u google the same query but replace with Android instead of iOS

**Comment by itayganor** [comment]
Why do you think it's related to tap delay? Anyway, I have:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
In the page header.

I also added :
```css
html {
    touch-action: manipulation;
}
```

to make sure there's no delay, and the problem persists :\

**Comment by itayganor** [comment]
Just to make sure it isn't touch related, I added this to my code:
```js
soundManager.chatIn.play();
window.navigator.vibrate(200);
```

The vibration indeed starts like a half-a-second before the sound.

**Comment by wle8300** [comment]
Nice test! Yea it’s a lame aspect of web on iOS/Android

**Comment by itayganor** [comment]
This might be easy to solve. What if you move this part to the constructor?
```js
    const audioElement = new Audio(this.file);
    audioElement.load();
    audioElement.addEventListener("loadeddata", () => {
...
```

**Comment by wle8300** [comment]
Would you mind creating a PR and testing if this solves your problem?

**Comment by itayganor** [comment]
I ended up using Howler since I didn't have the time to create a PR. Sorry and thanks anyway!
