### ISSUE TITLE
iOS UIfx says: "had a problem ..." for autoplay

### ISSUE THREAD

**Issue by Krakof** [wle8300/uifx#23]
Hi,
Could you please help me with this issue:
[https://codesandbox.io/s/gifted-sinoussi-pvco6](https://codesandbox.io/s/gifted-sinoussi-pvco6)

My goal is to play notification sound on event(new article arrived)

Found iOS Safari Chrome
Only autoplaying sound
Thanks in advance

**Comment by Krakof** [comment]
@wle8300  Sorry, could you please explain why you closed the issue w/o any notes may be I missed smth?

**Comment by wle8300** [comment]
What’s your bug/feature that you’re requesting?

**Comment by Krakof** [comment]
How can I play audio signal w/o user interaction e.g. when get new order? 


```
import bell from "./file.mp3"
let tick = new UIfx(bell)
...
componentDidUpdate() {
  if (hasNewSound) {
     tick = new UIfx(newSoundLink)
  }

  if (hasNewOrder) {
      tick.play()
  }
}
```
It doesn't work at iOS Safari or Chrome: UIfx says: "had a problem ...". But if I have a button which user can click everything is ok
Thanks in advance

**Comment by wle8300** [comment]
If you visit this page on your phone, do the sounds play?

http://www.wle8300.com/uifx-demo/

**Comment by Krakof** [comment]
iPhone
1. yes 
2. no

Android
both yes

Anyway I need to play sound w/o user interaction is it possible with your library?

**Comment by wle8300** [comment]
Have you read the docs?

**Comment by Krakof** [comment]
Yes, that's the problem, I didn't get the result that I expected. Can you please check the link I posted above. Sound does not play

**Comment by jasonejavier** [comment]
Same issue here
