### ISSUE TITLE
Unable to set volume to 0

### ISSUE THREAD

**Issue by heatherlumby** [wle8300/uifx#24]
I recently tried to set the volume to 0 and noticed that the sounds seemed to be getting louder insead of being muted. Looking through the code, I found the likely cause of this in src/index.js:

```
const validateVolume = volume => {
      const message = '"Volume" must be an number between 0.0 and 1.0';

      if (volume && typeof volume !== "number") throw Error(message);
      if (volume < 0 || volume > 1) throw Error(message);

      return volume ? volume : 1.0;
    };
```

It seems that the condition `volume ? volume : 1.0;` is returning a volume of 1.0 if volume is set to 0, as 0 is falsey.

**Comment by wle8300** [comment]
Hi Heather, i got this email. I’ll get back to you if we update the code. Thx for bringing this up!
