### ISSUE TITLE
Multiple uploads of the same file

### ISSUE THREAD

**Issue by eliarhsamos** [wle8300/uifx#26]
if i has
```
const beep = new UIfx(beepMp3);
const beep2 = new UIfx(beepMp3);
```
than

```
<audio id="uifx-1691122363" src="/_/build/4ad0857334c7e9db1ca2d6584d9de0ce.mp3" preload="auto"></audio>
<audio id="uifx-1691122363" src="/_/build/4ad0857334c7e9db1ca2d6584d9de0ce.mp3" preload="auto"></audio>
```

**Comment by wle8300** [comment]
@eliarhsamos have you tried doing this? i think that's possible without any changes to `uifx`

**Comment by eliarhsamos** [comment]
@wle8300 After creating a duplicate, you can delete it. But it's much better and easier, just don't create it. I have attached a fix https://github.com/wle8300/uifx/pull/27/files
