### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by skube** [wle8300/uifx#8]
Are the types for this lib?

**Comment by wle8300** [comment]
I’ve never used TypeScript. Not sure how to do this

**Comment by wle8300** [comment]
Let me know if you wanna work on this. Closing for now.

**Comment by kirill578** [comment]
add `index.d.ts` with the following:
```
declare module 'uifx' {
    type config = {
        volume?: number;
        throttleMs?: number;
    };

    export default class UIFx {
        constructor(file: string, config?: config) {
        }

        play: (volume: number) => UIFx;
        setVolume: (volume: number) => UIFx;
    }
}
```

**Comment by wle8300** [comment]
What’s the benefit for you as a TypeScript user?

Do you know if this would impact people who aren’t using TypeScript?

**Comment by kirill578** [comment]
* The code won't compile unless types are defined.
* The should not be any impact on JS users

 Also when publishing make sure to add 
```"types": "index.d.ts",```
in the `package.json`

**Comment by wle8300** [comment]
This seems like a worthwhile feature.

Can you create the PR? I will test it to ensure it works. Thx!

**Comment by wle8300** [comment]
@kirill578 Please let me know if you can create a PR. I may not be the best person to implement this since I have never used TypeScript. Thx!

**Comment by wle8300** [comment]
@kirill578 @skube 

I've updated the package to include TypeScript definitions. I just followed what @kirill578 directed me to do. Hopefully it works for yall!

https://www.npmjs.com/package/uifx

**Comment by fortysixcode** [comment]
Hi there, it seems that the types are missing from the version published on npm. If it is wanted I have created a PR (#14) so that the types are added to the build folder when building.

Thanks for UIfx!

**Comment by wle8300** [comment]
Thx Ben I appreciate your help! I’m not a TypeScript user myself so happy to use your expertise. 

I’ll review the PR tnite and should be ready tmrw morn. I’ll ping you here?

🌲 🎄

**Comment by wle8300** [comment]
@fortysixcode

Just published to Npm (https://www.npmjs.com/package/uifx). Thank you for your contribution! Merry Christmas!

**Comment by fortysixcode** [comment]
Awesome, thank you! Merry Christmas to you too.
