### ISSUE TITLE
DOMException: play() failed because the user didn't interact with the document first

### ISSUE THREAD

**Issue by clytras** [wle8300/uifx#9]
Hello, thanks for this simple utility.

I have a sound playing on every websocket update (Firebase) and those updates happen as soon as page loads, so I get the following error:

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.
```

To solve this, you can either add an error handling to the promise directly; or make [`play`](https://github.com/wle8300/uifx/blob/02318e4bec1315cbde5c5b8da142cd452e4b0976/src/index.js#L74) return a `Promise` with `audioElement.play()` result.

Something like this:

```
  play = volume => new Promise((resolve, reject) => {
    this.validateVolume(volume);

    const audioElement = new Audio(this.file);
    audioElement.load();

    audioElement.addEventListener("loadeddata", () => {
      audioElement.volume = volume >= 0 && volume <= 1 ? volume : this.volume;
      audioElement.play().then(resolve).catch(reject);
    });

    audioElement.addEventListener("error", reject);
  });
```

**Comment by wle8300** [comment]
Thx for catching this! Can you put together a PR for this?

I’ll gladly test and ping a follow-up msg once I’ve tested it

**Comment by clytras** [comment]
Of course, but if we make it like this, it will break the default behavior that has right now, which is that the `play` method returns the actual object so it will be [chainable](https://github.com/wle8300/uifx/blob/02318e4bec1315cbde5c5b8da142cd452e4b0976/src/index.js#L85).

For example it will break something like this `UIfxAudio.play().setVolume(.5)`. `play` method won't be chainable any more because it will return a proper promise (_which I beleive is the right way to be_).
If you don't have a problem with that, then I will send a PR tomorrow.

**Comment by wle8300** [comment]
You might wanna checkout some DDG searches on this: https://duckduckgo.com/?q=Uncaught+(in+promise)+DOMException%3A+play()+failed+because+the+user+didn%27t+interact+with+the+document+first.&t=canonical&ia=web

There seems to be a way to fix this without Promisifying the lib.

**Comment by clytras** [comment]
Promises are awesome and you should do some reasearch of the benefits using promises.
There is no way to catch that error because it rejects the promise returned by the [`play`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) method.

I suggest you read these API documents:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

Anyway, I can't teach you promises. I will fork this lib and promisify it as it should be. Thanks again.

**Comment by nekdev** [comment]
i also have this problem. how can I solve this?

**Comment by wle8300** [comment]
@clytras  Boop! :sparkle: 

![boop-da-snoot](https://user-images.githubusercontent.com/150245/68790243-c6e44400-05fb-11ea-90d5-b87505938f4b.png)

**Comment by clytras** [comment]
@wle8300 what's that about?

**Comment by wle8300** [comment]
I dunno. That guy looks like you and has your name lol... maybe you can figure it out! 👏👏👏👏

**Comment by clytras** [comment]
Really now? I'm still waiting you to answer about the supposed `try ... catch` solution that is **"working"**... It’s not your fault, it’s my fault that tried to help you out and wasted my time here. Keep studing because you still have a lot to learn about javascript. 😞 Good luck 🔥

**Comment by nekdev** [comment]
@wle8300 how is our portal related to this problem?

**Comment by clytras** [comment]
@nekdev don't watse your time here. The author is trying to figure our dark and mysterious conspiracy theories. I have created my package that does the same thing and that properly handles errors. You can find it here https://www.npmjs.com/package/uiplay
